version: "3"
services:
  flags-database:
    build: .
    ports:
      - "5002:80"
    restart: unless-stopped
    depends_on:
      - flags-database-db
  flags-database-db:
    image: mysql:5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fn983hbf3873
    volumes:
      - ./src/db/:/docker-entrypoint-initdb.d
